version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farm_network

volumes:
  postgres_data:

networks:
  farm_network:
    driver: bridge
